name: book_finder_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # ✅ Clean Architecture & Core
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5
  shimmer: ^3.0.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  lottie: ^2.7.0

  # ✅ Networking
  dio: ^5.3.3

  # ✅ JSON Serialization
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # ✅ Code Generation
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  # ✅ Unit Testing
  bloc_test: ^9.1.5
  mockito: ^5.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/book_loader.json
